<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Person extends \Google\Protobuf\Internal\Message
{
    
    protected $name = '';
    protected $age = 0;
    private $address;

    public function __construct($data = NULL) {
        \GPBMetadata\Person::initOnce();
        parent::__construct($data);
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }
   
    
    public function getAge()
    {
        return $this->age;
    }

    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->age = $var;

        return $this;
    }

   
    public function getAddress()
    {
        return $this->address;
    }

    public function setAddress($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->address = $arr;

        return $this;
    }
}